/**
 * PipedriveAPIV1Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Data2
 */
class Data32 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.title = this.constructor.getValue(obj.title);
        this.owner_id = this.constructor.getValue(obj.owner_id);
        this.creator_id = this.constructor.getValue(obj.creator_id);
        this.person_id = this.constructor.getValue(obj.person_id);
        this.organization_id = this.constructor.getValue(obj.organization_id);
        this.is_archived = this.constructor.getValue(obj.is_archived);
        this.source_name = this.constructor.getValue(obj.source_name);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'title', realName: 'title' },
            { name: 'owner_id', realName: 'owner_id' },
            { name: 'creator_id', realName: 'creator_id' },
            { name: 'person_id', realName: 'person_id', type: 'PersonId' },
            { name: 'org_id', realName: 'org_id', type: 'OrgId' },
            { name: 'is_archived', realName: 'is_archived' },
            { name: 'source_name', realName: 'source_name' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Data32;
